# Generated by Django 3.1.7 on 2021-05-05 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCToken',
            fields=[
                ('name', models.CharField(help_text='Project name', max_length=80, verbose_name='project name')),
                ('symbol', models.CharField(help_text='Token symbol', max_length=20, verbose_name='token symbol')),
                ('contract_address', models.CharField(help_text='Contract address', max_length=42, primary_key=True, serialize=False, unique=True)),
                ('launch_date', models.DateTimeField(blank=True, help_text='Project launch date, format: YYYY-MM-DD HH:MM:SS', null=True)),
                ('website', models.URLField(blank=True, help_text='Project website URL link', verbose_name='project website')),
                ('description', models.TextField(blank=True, help_text='Projects purpose or future details', verbose_name='project description')),
                ('whitepaper', models.URLField(blank=True, help_text='Project whitepaper URL link', verbose_name='project whitepaper')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates the token has been archived.', verbose_name='archived')),
                ('creator', models.ForeignKey(help_text='User who created the BSCToken.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Binance Smart Chain Token',
                'verbose_name_plural': 'Binance Smart Chain Tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenSocials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('blog', models.URLField(blank=True)),
                ('reddit', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('token', models.ForeignKey(db_column='token', on_delete=django.db.models.deletion.CASCADE, to='crypto.bsctoken')),
            ],
            options={
                'verbose_name': 'Socials',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='SwapTransaction',
            fields=[
                ('hash', models.CharField(blank=True, help_text='Transaction hash', max_length=66, primary_key=True, serialize=False, unique=True, verbose_name='TxHash')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Transaction timestamp')),
                ('from_amount', models.FloatField(help_text='Token amount swapped from')),
                ('from_price', models.FloatField(blank=True, help_text='Token price swapped from', null=True)),
                ('to_amount', models.FloatField(help_text='Token amount swapped to')),
                ('to_price', models.FloatField(blank=True, help_text='Token price swapped to', null=True)),
                ('fee', models.FloatField(blank=True, help_text='Amount of BNB paid to miners for swap transaction', verbose_name='transaction fee')),
                ('from_token', models.ForeignKey(blank=True, db_column='from_token', help_text='Token swapped from', on_delete=django.db.models.deletion.PROTECT, related_name='swaps_from_token', to='crypto.bsctoken')),
                ('to_token', models.ForeignKey(db_column='to_token', help_text='Token swapped to', on_delete=django.db.models.deletion.PROTECT, related_name='swaps_to_token', to='crypto.bsctoken')),
            ],
            options={
                'verbose_name': 'Swap Transaction',
                'verbose_name_plural': 'Swap Transactions',
            },
        ),
        migrations.AddField(
            model_name='bsctoken',
            name='socials',
            field=models.ForeignKey(blank=True, db_column='socials', null=True, on_delete=django.db.models.deletion.CASCADE, to='crypto.tokensocials'),
        ),
        migrations.AddField(
            model_name='bsctoken',
            name='swaps',
            field=models.ManyToManyField(blank=True, to='crypto.SwapTransaction'),
        ),
    ]
