import {Blog} from './blog';

export const BLOGS: Blog[] = [
  { id: 0,
    title: 'Learn how Angular Elements transmits Component’s @Outputs outside Angular',
    subtitle: 'Angular Component @Outputs',
    content: 'In our last article we described how Angular Elements works under the hood. We identified that Angular Elements is a bridge to connect Custom Elements to Angular Components.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3000/1500' },
  { id: 1,
    title: 'Angular CDK Tables',
    subtitle: '',
    content: 'In this article: Angular CDK Tables, Bootstrap 4 with Angular CDK Tables, Client Side searching/paging/sorting.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/1000/500' },
  { id: 2,
    title: 'One-way template expression binding mechanism in Angular',
    subtitle: '',
    content: 'Angular is the most popular and widely used JavaScript framework after React.js. It abstracts many complexities away from developers to enable them to develop apps with ease.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3002' },
  { id: 3,
    title: 'The Extensive Guide to Creating Streams in RxJS',
    subtitle: '',
    content: 'For most developers the first contact with RxJS is established by libraries, like Angular. Some functions return streams and to make use of them the focus naturally is on operators.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3003' },
  { id: 4,
    title: 'RxJS: Avoiding Unbound Methods',
    subtitle: '',
    content: 'When unbound methods are passed to RxJS, they will be invoked with an unexpected context for this. If the method implementations don’t use this, they will behave as you would expect.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3004' },
  { id: 5,
    title: 'Angular Elements: how does this magic work under the hood?',
    subtitle: 'Nvidia RTX Titan X Graphics Card.',
    content: 'The Angular Elements project is generating lots of hype in the community right now, and rightly so! Angular Elements provides a wealth of awesome features out of the box.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://res.cloudinary.com/anonymous-one/image/upload/v1589155533/CyberSecurityWebsite/HiRes_RTXTitan_GPU_Original_j8dom3.jpg' },
  { id: 6,
    title: 'RxJS: Testing with Fake Time',
    subtitle: '',
    content: 'Angular, Jasmine, Jest and Sinon.JS all provide APIs for running tests with fake time. Their APIs differ, but they are broadly similar. Running tests with fake time avoids having to wait for actual time to elapse and it also makes the tests much simpler, as they run synchronously. So what does this have to do with RxJS?',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3006' },
  { id: 7,
    title: 'How do CDK Portals work?',
    subtitle: '',
    content: 'In the last article we were exploring how to leverage the Angular Material CDK portals for placing some piece of template from a component to some other location within our app. CDK portals make this a no-brainer. Wondering how they work? In this article we dive deeper to uncover how its internals work and how we could simply implement it by ourselves.',
    author: 'Anonymous One',
    date: 'Apr 28, 2020',
    readtime: 0,
    image: 'https://picsum.photos/3007' },
];
